# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title createTanimotoMatrix
#' @description
#' Function to calculate all pairwise Tanimoto similarities for one set of fingerprints
#' @param fingerprints Matrix with 0/1 values (rows: compounds, columns: fingerprint features)
#' @param oldMatrix Optional numeric matrix with precalculated similarities. The corresponding part of the
#' result matrix will be copied, rather than recalculated Logical, indicates wheter oldMatrix should be used
#' @return square matrix with Tanimoto similarities
#' @author Marvin Steijaert
#' @export
#' @examples a=matrix(sample(0:1,100,TRUE),10,10);b=matrix(1:4,2,2);createTanimotoMatrix(a,b)
createTanimotoMatrix <- function(fingerprints, oldMatrix = matrix()) {
    .Call('_dartTools_createTanimotoMatrix', PACKAGE = 'dartTools', fingerprints, oldMatrix)
}

#' @title createAsymmetricTanimotoMatrix
#' @description
#' Function to calculate all pairwise Tanimoto similarities between two sets of fingerprints
#' @param fingerprintsA Matrix with 0/1 values (rows: compounds, columns: fingerprint features)
#' @param fingerprintsB Matrix with 0/1 values (rows: compounds, columns: fingerprint features)
#' @return matrix with Tanimoto similarities
#'
#' @author Marvin Steijaert
createAsymmetricTanimotoMatrix <- function(fingerprintsA, fingerprintsB) {
    .Call('_dartTools_createAsymmetricTanimotoMatrix', PACKAGE = 'dartTools', fingerprintsA, fingerprintsB)
}

